var i = 0;
var t = 0;
var nlclass = "class";
var nlclassPatch = "class";

nltree[i] = "Balance"; i++;
nltree[i] = "Feral Combat"; i++;
nltree[i] = "DRestoration"; i++;
nltree[i] = "Beast Mastery"; i++;
nltree[i] = "Marksmanship"; i++;
nltree[i] = "Survival"; i++;
nltree[i] = "Arcane"; i++;
nltree[i] = "Fire"; i++;
nltree[i] = "Frost"; i++;
nltree[i] = "PaHoly"; i++;
nltree[i] = "Protection"; i++;
nltree[i] = "Retribution"; i++;
nltree[i] = "Discipline"; i++;
nltree[i] = "PrHoly"; i++;
nltree[i] = "Shadow"; i++;
nltree[i] = "Assassination"; i++;
nltree[i] = "Combat"; i++;
nltree[i] = "Subtlety"; i++;
nltree[i] = "Elemental"; i++;
nltree[i] = "Enhancement"; i++;
nltree[i] = "SRestoration"; i++;
nltree[i] = "Affliction"; i++;
nltree[i] = "Demonology"; i++;
nltree[i] = "Destruction"; i++;
nltree[i] = "Arms"; i++;
nltree[i] = "Fury"; i++;
nltree[i] = "Protection"; i++;

i = 0;

//balance talents
nltalent[i] = ["Starlight Wrath"]; i++;
nltalent[i] = ["Genesis"]; i++;
nltalent[i] = ["Moonglow"]; i++;
nltalent[i] = ["Nature's Mastery"]; i++;
nltalent[i] = ["Improved Moonfire"]; i++;
nltalent[i] = ["Brambles"]; i++;
nltalent[i] = ["Nature's Grace"]; i++;
nltalent[i] = ["Nature's Splendor"]; i++;
nltalent[i] = ["Nature's Reach"]; i++;
nltalent[i] = ["Vengeance"]; i++;
nltalent[i] = ["Celestial Focus"]; i++;
nltalent[i] = ["Lunar Guidance"]; i++;
nltalent[i] = ["Insect Swarm"]; i++;
nltalent[i] = ["Improved Insect Swarm"]; i++;
nltalent[i] = ["Dreamstate"]; i++;
nltalent[i] = ["Moonfury"]; i++;
nltalent[i] = ["Balance of Power"]; i++;
nltalent[i] = ["Moonkin Form"]; i++;
nltalent[i] = ["Improved Moonkin Form"]; i++;
nltalent[i] = ["Improved Faerie Fire"]; i++;
nltalent[i] = ["Owlkin Frenzy"]; i++;
nltalent[i] = ["Wrath of Cenarius"]; i++;
nltalent[i] = ["Eclipse"]; i++;
nltalent[i] = ["Typhoon"]; i++;
nltalent[i] = ["Force of Nature"]; i++;
nltalent[i] = ["Gale Winds"]; i++;
nltalent[i] = ["Earth and Moon"]; i++;
nltalent[i] = ["Starfall"]; i++;
treeStartStop[t] = i -1;
t++;

//feral talents
nltalent[i] = ["Ferocity"]; i++;
nltalent[i] = ["Feral Aggression"]; i++;
nltalent[i] = ["Feral Instinct"]; i++;
nltalent[i] = ["Savage Fury"]; i++;
nltalent[i] = ["Thick Hide"]; i++;
nltalent[i] = ["Feral Swiftness"]; i++;
nltalent[i] = ["Survival Instincts"]; i++;
nltalent[i] = ["Sharpened Claws"]; i++;
nltalent[i] = ["Shredding Attacks"]; i++;
nltalent[i] = ["Predatory Strikes"]; i++;
nltalent[i] = ["Primal Fury"]; i++;
nltalent[i] = ["Primal Precision"]; i++;
nltalent[i] = ["Brutal Impact"]; i++;
nltalent[i] = ["Feral Charge"]; i++;
nltalent[i] = ["Nurturing Instinct"]; i++;
nltalent[i] = ["Natural Reaction"]; i++
nltalent[i] = ["Heart of the Wild"]; i++;
nltalent[i] = ["Survival of the Fittest"]; i++;
nltalent[i] = ["Leader of the Pack"]; i++;
nltalent[i] = ["Improved Leader of the Pack"]; i++;
nltalent[i] = ["Primal Tenacity"]; i++;
nltalent[i] = ["Protector of the Pack"]; i++;
nltalent[i] = ["Predatory Instincts"]; i++;
nltalent[i] = ["Infected Wounds"]; i++;
nltalent[i] = ["King of the Jungle"]; i++;
nltalent[i] = ["Mangle"]; i++;
nltalent[i] = ["Improved Mangle"]; i++;
nltalent[i] = ["Rend and Tear"]; i++;
nltalent[i] = ["Primal Gore"]; i++;
nltalent[i] = ["Berserk"]; i++;

treeStartStop[t] = i -1;
t++;

//restoration talents

nltalent[i] = ["Improved Mark of the Wild"]; i++;
nltalent[i] = ["Nature's Focus"]; i++;
nltalent[i] = ["Furor"]; i++;
nltalent[i] = ["Naturalist"]; i++;
nltalent[i] = ["Subtlety"]; i++;
nltalent[i] = ["Natural Shapeshifter"]; i++;
nltalent[i] = ["Intensity"]; i++;
nltalent[i] = ["Omen of Clarity"]; i++;
nltalent[i] = ["Master Shapeshifter"]; i++;
nltalent[i] = ["Tranquil Spirit"]; i++;
nltalent[i] = ["Improved Rejuvenation"]; i++;
nltalent[i] = ["Nature's Swiftness"]; i++;
nltalent[i] = ["Gift of Nature"]; i++;
nltalent[i] = ["Improved Tranquility"]; i++;
nltalent[i] = ["Empowered Touch"]; i++;
nltalent[i] = ["Improved Regrowth"]; i++;
nltalent[i] = ["Living Spirit"]; i++;
nltalent[i] = ["Swiftmend"]; i++;
nltalent[i] = ["Natural Perfection"]; i++;
nltalent[i] = ["Empowered Rejuvenation"]; i++;
nltalent[i] = ["Living Seed"]; i++;
nltalent[i] = ["Replenish"]; i++;
nltalent[i] = ["Tree of Life"]; i++;
nltalent[i] = ["Improved Tree of Life"]; i++;
nltalent[i] = ["Improved Barkskin"]; i++;
nltalent[i] = ["Gift of the Earthmother"]; i++;
nltalent[i] = ["Wild Growth"]; i++;

treeStartStop[t] = i -1;
t++;

//beastmaster talents
nltalent[i] = ["Improved Aspect of the Hawk"]; i++;
nltalent[i] = ["Endurance Training"]; i++;
nltalent[i] = ["Focused Fire"]; i++;
nltalent[i] = ["Improved Aspect of the Monkey"]; i++; 
nltalent[i] = ["Thick Hide"]; i++;
nltalent[i] = ["Improved Revive Pet"]; i++;
nltalent[i] = ["Pathfinding"]; i++;
nltalent[i] = ["Aspect Mastery"]; i++;
nltalent[i] = ["Unleashed Fury"]; i++;
nltalent[i] = ["Improved Mend Pet"]; i++;
nltalent[i] = ["Ferocity"]; i++;
nltalent[i] = ["Spirit Bond"]; i++;
nltalent[i] = ["Intimidation"]; i++;
nltalent[i] = ["Bestial Discipline"]; i++;
nltalent[i] = ["Animal Handler"]; i++;
nltalent[i] = ["Frenzy"]; i++;
nltalent[i] = ["Ferocious Inspiration"]; i++;
nltalent[i] = ["Bestial Wrath"]; i++;
nltalent[i] = ["Catlike Reflexes"]; i++;
nltalent[i] = ["Invigoration"]; i++;
nltalent[i] = ["Serpent's Swiftness"]; i++;
nltalent[i] = ["Longevity"]; i++;
nltalent[i] = ["The Beast Within"]; i++;
nltalent[i] = ["Cobra Strikes"]; i++;
nltalent[i] = ["Kindred Spirits"]; i++;
nltalent[i] = ["Beast Mastery"]; i++;
treeStartStop[t] = i -1;
t++;

//marksmanship talents
nltalent[i] = ["Improved Concussive Shot"]; i++;
nltalent[i] = ["Focused Aim"]; i++;
nltalent[i] = ["Lethal Shots"]; i++;
nltalent[i] = ["Careful Aim"]; i++;
nltalent[i] = ["Improved Hunter's Mark"]; i++;
nltalent[i] = ["Mortal Shots"]; i++;
nltalent[i] = ["Go for the Throat"]; i++;
nltalent[i] = ["Improved Arcane Shot"]; i++;
nltalent[i] = ["Aimed Shot"]; i++;
nltalent[i] = ["Rapid Killing"]; i++;
nltalent[i] = ["Improved Stings"]; i++;
nltalent[i] = ["Efficiency"]; i++;
nltalent[i] = ["Concussive Barrage"]; i++;
nltalent[i] = ["Readiness"]; i++;
nltalent[i] = ["Barrage"]; i++;
nltalent[i] = ["Combat Experience"]; i++;
nltalent[i] = ["Ranged Weapon Specialization"]; i++;
nltalent[i] = ["Piercing Shots"]; i++;
nltalent[i] = ["Trueshot Aura"]; i++;
nltalent[i] = ["Improved Barrage"]; i++;
nltalent[i] = ["Master Marksman"]; i++;
nltalent[i] = ["Rapid Recuperation"]; i++;
nltalent[i] = ["Wild Quiver"]; i++;
nltalent[i] = ["Silencing Shot"]; i++;
nltalent[i] = ["Improved Steady Shot"]; i++;
nltalent[i] = ["Marked for Death"]; i++;
nltalent[i] = ["Chimera Shot"]; i++;
treeStartStop[t] = i -1;
t++;

//Survival talents
nltalent[i] = ["Improved Tracking"]; i++;
nltalent[i] = ["Hawk Eye"]; i++;
nltalent[i] = ["Savage Strikes"]; i++;
nltalent[i] = ["Surefooted"]; i++;
nltalent[i] = ["Entrapment"]; i++;
nltalent[i] = ["Trap Mastery"]; i++;
nltalent[i] = ["Survival Instincts"]; i++;
nltalent[i] = ["Survivalist"]; i++;
nltalent[i] = ["Scatter Shot"]; i++;
nltalent[i] = ["Deflection"]; i++;
nltalent[i] = ["Survival Tactics"]; i++;
nltalent[i] = ["T.N.T."]; i++;
nltalent[i] = ["Lock and Load"]; i++;
nltalent[i] = ["Hunter vs. Wild"]; i++;
nltalent[i] = ["Killer Instinct"]; i++;
nltalent[i] = ["Counterattack"]; i++;
nltalent[i] = ["Lightning Reflexes"]; i++;
nltalent[i] = ["Resourcefulness"]; i++;
nltalent[i] = ["Expose Weakness"]; i++;
nltalent[i] = ["Wyvern Sting"]; i++;
nltalent[i] = ["Thrill of the Hunt"]; i++;
nltalent[i] = ["Master Tactician"]; i++;
nltalent[i] = ["Noxious Stings"]; i++;
nltalent[i] = ["Point of No Escape"]; i++;
nltalent[i] = ["Black Arrow"]; i++;
nltalent[i] = ["Sniper Training"]; i++;
nltalent[i] = ["Hunting Party"]; i++;
nltalent[i] = ["Explosive Shot"]; i++;
treeStartStop[t] = i -1;
t++;

//arcane talents
nltalent[i] = ["Arcane Subtlety"]; i++;
nltalent[i] = ["Arcane Focus"]; i++;
nltalent[i] = ["Arcane Stability"]; i++;
nltalent[i] = ["Arcane Fortitude"]; i++;
nltalent[i] = ["Magic Absorption"]; i++;
nltalent[i] = ["Arcane Concentration"]; i++;
nltalent[i] = ["Magic Attunement"]; i++;
nltalent[i] = ["Spell Impact"]; i++;
nltalent[i] = ["Student of the Mind"]; i++;
nltalent[i] = ["Focus Magic"]; i++;
nltalent[i] = ["Arcane Shielding"]; i++;
nltalent[i] = ["Improved Counterspell"]; i++;
nltalent[i] = ["Arcane Meditation"]; i++;
nltalent[i] = ["Torment the Weak"]; i++;
nltalent[i] = ["Improved Blink"]; i++;
nltalent[i] = ["Presence of Mind"]; i++;
nltalent[i] = ["Arcane Mind"]; i++;
nltalent[i] = ["Prismatic Cloak"]; i++;
nltalent[i] = ["Arcane Instability"]; i++;
nltalent[i] = ["Arcane Potency"]; i++;
nltalent[i] = ["Arcane Empowerment"]; i++;
nltalent[i] = ["Arcane Power"]; i++;
nltalent[i] = ["Incanter's Absorption"]; i++;
nltalent[i] = ["Arcane Flows"]; i++;
nltalent[i] = ["Mind Mastery"]; i++;
nltalent[i] = ["Slow"]; i++;
nltalent[i] = ["Missile Barrage"]; i++;
nltalent[i] = ["Netherwind Presence"]; i++;
nltalent[i] = ["Spell Power"]; i++;
nltalent[i] = ["Arcane Barrage"]; i++;
treeStartStop[t] = i -1;
t++;

//fire talents
nltalent[i] = ["Improved Fire Blast"]; i++;
nltalent[i] = ["Incineration"]; i++;
nltalent[i] = ["Improved Fireball"]; i++;
nltalent[i] = ["Ignite"]; i++;
nltalent[i] = ["Burning Determination"]; i++;
nltalent[i] = ["World in Flames"]; i++;
nltalent[i] = ["Flame Throwing"]; i++;
nltalent[i] = ["Impact"]; i++;
nltalent[i] = ["Pyroblast"]; i++;
nltalent[i] = ["Burning Soul"]; i++;
nltalent[i] = ["Improved Scorch"]; i++;
nltalent[i] = ["Molten Shields"]; i++;
nltalent[i] = ["Master of Elements"]; i++;
nltalent[i] = ["Playing with Fire"]; i++;
nltalent[i] = ["Critical Mass"]; i++;
nltalent[i] = ["Blast Wave"]; i++;
nltalent[i] = ["Blazing Speed"]; i++;
nltalent[i] = ["Fire Power"]; i++;
nltalent[i] = ["Pyromaniac"]; i++;
nltalent[i] = ["Combustion"]; i++;
nltalent[i] = ["Molten Fury"]; i++;
nltalent[i] = ["Fiery Payback"]; i++;
nltalent[i] = ["Empowered Fire"]; i++;
nltalent[i] = ["Firestarter"]; i++;
nltalent[i] = ["Dragon's Breath"]; i++;
nltalent[i] = ["Hot Streak"]; i++;
nltalent[i] = ["Burnout"]; i++;
nltalent[i] = ["Living Bomb"]; i++;
treeStartStop[t] = i -1;
t++;

//frost talents
nltalent[i] = ["Frostbite"]; i++;
nltalent[i] = ["Improved Frostbolt"]; i++;
nltalent[i] = ["Ice Floes"]; i++;
nltalent[i] = ["Ice Shards"]; i++;
nltalent[i] = ["Frost Warding"]; i++;
nltalent[i] = ["Elemental Precision"]; i++;
nltalent[i] = ["Permafrost"]; i++;
nltalent[i] = ["Piercing Ice"]; i++;
nltalent[i] = ["Icy Veins"]; i++;
nltalent[i] = ["Improved Blizzard"]; i++;
nltalent[i] = ["Arctic Reach"]; i++;
nltalent[i] = ["Frost Channeling"]; i++;
nltalent[i] = ["Shatter"]; i++;
nltalent[i] = ["Cold Snap"]; i++;
nltalent[i] = ["Improved Cone of Cold"]; i++;
nltalent[i] = ["Frozen Core"]; i++;
nltalent[i] = ["Cold as Ice"]; i++;
nltalent[i] = ["Winter's Chill"]; i++;
nltalent[i] = ["Shattered Barrier"]; i++;
nltalent[i] = ["Ice Barrier"]; i++;
nltalent[i] = ["Arctic Winds"]; i++;
nltalent[i] = ["Empowered Frostbolt"]; i++;
nltalent[i] = ["Fingers of Frost"]; i++;
nltalent[i] = ["Brain Freeze"]; i++;
nltalent[i] = ["Summon Water Elemental"]; i++;
nltalent[i] = ["Improved Water Elemental"]; i++;
nltalent[i] = ["Chilled to the Bone"]; i++;
nltalent[i] = ["Deep Freeze"]; i++;
treeStartStop[t] = i -1;
t++;

//holy talents
nltalent[i] = ["Spiritual Focus"]; i++;
nltalent[i] = ["Seals of the Pure"]; i++; 
nltalent[i] = ["Healing Light"]; i++;
nltalent[i] = ["Divine Intellect"]; i++;
nltalent[i] = ["Unyielding Faith"]; i++;
nltalent[i] = ["Aura Mastery"]; i++;
nltalent[i] = ["Illumination"]; i++;
nltalent[i] = ["Improved Lay on Hands"]; i++;
nltalent[i] = ["Improved Concentration Aura"]; i++;
nltalent[i] = ["Improved Blessing of Wisdom"]; i++;
nltalent[i] = ["Pure of Heart"]; i++;
nltalent[i] = ["Divine Favor"]; i++;
nltalent[i] = ["Sanctified Light"]; i++;
nltalent[i] = ["Blessed Hands"]; i++;
nltalent[i] = ["Purifying Power"]; i++;
nltalent[i] = ["Holy Power"]; i++;
nltalent[i] = ["Light's Grace"]; i++;
nltalent[i] = ["Holy Shock"]; i++;
nltalent[i] = ["Blessed Life"]; i++;
nltalent[i] = ["Infusion of Light"]; i++;
nltalent[i] = ["Holy Guidance"]; i++;
nltalent[i] = ["Sacred Cleansing"]; i++;
nltalent[i] = ["Divine Illumination"]; i++;
nltalent[i] = ["Enlightened Judgements"]; i++;
nltalent[i] = ["Judgements of the Pure"]; i++;
nltalent[i] = ["Beacon of Light"]; i++;
treeStartStop[t] = i -1;
t++;

//protection talents

nltalent[i] = ["Divinity"]; i++;
nltalent[i] = ["Divine Strength"]; i++;
nltalent[i] = ["Stoicism"]; i++;
nltalent[i] = ["Guardians Favor"]; i++;
nltalent[i] = ["Anticipation"]; i++;
nltalent[i] = ["Divine Sacrifice"]; i++;
nltalent[i] = ["Improved Righteous Fury"]; i++;
nltalent[i] = ["Toughness"]; i++;
nltalent[i] = ["Divine Guardian"]; i++;
nltalent[i] = ["Improved Hammer of Justice"]; i++;
nltalent[i] = ["Improved Devotion Aura"]; i++;
nltalent[i] = ["Blessing of Sanctuary"]; i++;
nltalent[i] = ["Reckoning"]; i++;
nltalent[i] = ["Sacred Duty"]; i++;
nltalent[i] = ["One-Handed Weapon Specialization"]; i++;
nltalent[i] = ["Spiritual Attunement"]; i++;
nltalent[i] = ["Holy Shield"]; i++;
nltalent[i] = ["Ardent Defender"]; i++;
nltalent[i] = ["Redoubt"]; i++;
nltalent[i] = ["Combat Expertise"]; i++;
nltalent[i] = ["Touched by the Light"]; i++;
nltalent[i] = ["Avenger's Shield"]; i++;
nltalent[i] = ["Guarded by the Light"]; i++;
nltalent[i] = ["Shield of the Templar"]; i++;
nltalent[i] = ["Judgements of the Just"]; i++;
nltalent[i] = ["Hammer of the Righteous"]; i++;
treeStartStop[t] = i -1;
t++;


//retribution talents

nltalent[i] = ["Deflection"]; i++;
nltalent[i] = ["Benediction"]; i++;
nltalent[i] = ["Improved Judgements"]; i++;
nltalent[i] = ["Heart of the Crusader"]; i++;
nltalent[i] = ["Improved Blessing of Might"]; i++;
nltalent[i] = ["Vindication"]; i++;
nltalent[i] = ["Conviction"]; i++;
nltalent[i] = ["Seal of Command"]; i++;
nltalent[i] = ["Pursuit of Justice"]; i++;
nltalent[i] = ["Eye for an Eye"]; i++;
nltalent[i] = ["Sanctified Seals"]; i++;
nltalent[i] = ["Crusade"]; i++;
nltalent[i] = ["Two-Handed Weapon Specialization"]; i++;
nltalent[i] = ["Sanctified Retribution"]; i++;
nltalent[i] = ["Vengeance"]; i++;
nltalent[i] = ["Divine Purpose"]; i++;
nltalent[i] = ["The Art of War"]; i++;
nltalent[i] = ["Repentance"]; i++;
nltalent[i] = ["Judgement of the Wise"]; i++;
nltalent[i] = ["Fanaticism"]; i++;
nltalent[i] = ["Sanctified Wrath"]; i++;
nltalent[i] = ["Swift Retribution"]; i++;
nltalent[i] = ["Crusader Strike"]; i++;
nltalent[i] = ["Sheath of Light"]; i++;
nltalent[i] = ["Righteous Vengeance"]; i++;
nltalent[i] = ["Divine Storm"]; i++;
treeStartStop[t] = i -1;
t++;

//disc talents
nltalent[i] = ["Unbreakable Will"]; i++;
nltalent[i] = ["Twin Disciplines"]; i++;
nltalent[i] = ["Silent Resolve"]; i++;
nltalent[i] = ["Improved Inner Fire"]; i++;
nltalent[i] = ["Improved Power Word: Fortitude"]; i++;
nltalent[i] = ["Martyrdom"]; i++; 
nltalent[i] = ["Improved Power Word: Shield"]; i++;
nltalent[i] = ["Inner Focus"]; i++;
nltalent[i] = ["Meditation"]; i++;
nltalent[i] = ["Absolution"]; i++;
nltalent[i] = ["Mental Agility"]; i++;
nltalent[i] = ["Improved Mana Burn"]; i++;
nltalent[i] = ["Mental Strength"]; i++;
nltalent[i] = ["Divine Spirit"]; i++;
nltalent[i] = ["Improved Divine Spirit"]; i++;
nltalent[i] = ["Focused Power"]; i++;
nltalent[i] = ["Enlightenment"]; i++;
nltalent[i] = ["Focused Will"]; i++;
nltalent[i] = ["Power Infusion"]; i++;
nltalent[i] = ["Reflective Shield"]; i++;
nltalent[i] = ["Renewed Hope"]; i++;
nltalent[i] = ["Rapture"]; i++;
nltalent[i] = ["Aspiration"]; i++;
nltalent[i] = ["Divine Aegis"]; i++;
nltalent[i] = ["Pain Suppression"]; i++;
nltalent[i] = ["Grace"]; i++;
nltalent[i] = ["Borrowed Time"]; i++;
nltalent[i] = ["Penance"]; i++;

treeStartStop[t] = i -1;
t++;

//holy talents

nltalent[i] = ["Healing Focus"]; i++;
nltalent[i] = ["Improved Renew"]; i++;
nltalent[i] = ["Holy Specialization"]; i++;
nltalent[i] = ["Spell Warding"]; i++;
nltalent[i] = ["Divine Fury"]; i++;
nltalent[i] = ["Desperate Prayer"]; i++;
nltalent[i] = ["Blessed Recovery"]; i++;
nltalent[i] = ["Inspiration"]; i++;
nltalent[i] = ["Holy Reach"]; i++;
nltalent[i] = ["Improved Healing"]; i++;
nltalent[i] = ["Searing Light"]; i++;
nltalent[i] = ["Healing Prayers"]; i++;
nltalent[i] = ["Spirit of Redemption"]; i++;
nltalent[i] = ["Spiritual Guidance"]; i++;
nltalent[i] = ["Surge of Light"]; i++;
nltalent[i] = ["Spiritual Healing"]; i++;
nltalent[i] = ["Holy Concentration"]; i++;
nltalent[i] = ["Lightwell"]; i++;
nltalent[i] = ["Blessed Resilience"]; i++;
nltalent[i] = ["Body and Soul"]; i++;
nltalent[i] = ["Empowered Healing"]; i++;
nltalent[i] = ["Serendipity"]; i++;
nltalent[i] = ["Empowered Renew"]; i++;
nltalent[i] = ["Circle of Healing"]; i++;
nltalent[i] = ["Test of Faith"]; i++;
nltalent[i] = ["Divine Providence"]; i++;
nltalent[i] = ["Guardian Spirit"]; i++;
treeStartStop[t] = i -1;
t++;

//shadow talents

nltalent[i] = ["Spirit Tap"]; i++;
nltalent[i] = ["Improved Spirit Tap"]; i++;
nltalent[i] = ["Blackout"]; i++;
nltalent[i] = ["Shadow Affinity"]; i++;
nltalent[i] = ["Improved Shadow Word: Pain"]; i++;
nltalent[i] = ["Shadow Focus"]; i++;
nltalent[i] = ["Improved Psychic Scream"]; i++;
nltalent[i] = ["Improved Mind Blast"]; i++;
nltalent[i] = ["Mind Flay"]; i++;
nltalent[i] = ["Veiled Shadows"]; i++;
nltalent[i] = ["Shadow Reach"]; i++;
nltalent[i] = ["Shadow Weaving"]; i++;
nltalent[i] = ["Silence"]; i++;
nltalent[i] = ["Vampiric Embrace"]; i++;
nltalent[i] = ["Improved Vampiric Embrace"]; i++;
nltalent[i] = ["Focused Mind"]; i++;
nltalent[i] = ["Mind Melt"]; i++;
nltalent[i] = ["Improved Devouring Plague"]; i++;
nltalent[i] = ["Shadowform"]; i++;
nltalent[i] = ["Shadow Power"]; i++;
nltalent[i] = ["Improved Shadowform"]; i++;
nltalent[i] = ["Misery"]; i++;
nltalent[i] = ["Psychic Horror"]; i++;
nltalent[i] = ["Vampiric Touch"]; i++;
nltalent[i] = ["Pain and Suffering"]; i++;
nltalent[i] = ["Twisted Faith"]; i++;
nltalent[i] = ["Dispersion"]; i++;
treeStartStop[t] = i -1;
t++;

//assassin talents
nltalent[i] = ["Improved Eviscerate"]; i++;
nltalent[i] = ["Remorseless Attacks"]; i++;
nltalent[i] = ["Malice"]; i++;
nltalent[i] = ["Ruthlessness"]; i++; 
nltalent[i] = ["Blood Spatter"]; i++;
nltalent[i] = ["Puncturing Wounds"]; i++;
nltalent[i] = ["Vigor"]; i++;
nltalent[i] = ["Improved Expose Armor"]; i++;
nltalent[i] = ["Lethality"]; i++;
nltalent[i] = ["Vile Poisons"]; i++;
nltalent[i] = ["Improved Poisons"]; i++;
nltalent[i] = ["Fleet Footed"]; i++;
nltalent[i] = ["Cold Blood"]; i++;
nltalent[i] = ["Improved Kidney Shot"]; i++;
nltalent[i] = ["Quick Recovery"]; i++;
nltalent[i] = ["Seal Fate"]; i++;
nltalent[i] = ["Murder"]; i++;
nltalent[i] = ["Deadly Brew"]; i++;
nltalent[i] = ["Overkill"]; i++;
nltalent[i] = ["Deadened Nerves"]; i++;
nltalent[i] = ["Focused Attacks"]; i++;
nltalent[i] = ["Find Weakness"]; i++;
nltalent[i] = ["Master Poisoner"]; i++;
nltalent[i] = ["Mutilate"]; i++;
nltalent[i] = ["Turn the Tables"]; i++;
nltalent[i] = ["Cut to the Chase"]; i++;
nltalent[i] = ["Hunger For Blood"]; i++;
treeStartStop[t] = i -1;
t++;

//combat talents
nltalent[i] = ["Improved Gouge"]; i++;
nltalent[i] = ["Improved Sinister Strike"]; i++;
nltalent[i] = ["Dual Wield Specialization"]; i++;
nltalent[i] = ["Improved Slice and Dice"]; i++;
nltalent[i] = ["Deflection"]; i++;
nltalent[i] = ["Precision"]; i++;
nltalent[i] = ["Endurance"]; i++;
nltalent[i] = ["Riposte"]; i++;
nltalent[i] = ["Close Quarters Combat"]; i++;
nltalent[i] = ["Improved Kick"]; i++;
nltalent[i] = ["Improved Sprint"]; i++;
nltalent[i] = ["Lightning Reflexes"]; i++;
nltalent[i] = ["Aggression"]; i++;
nltalent[i] = ["Mace Specialization"]; i++;
nltalent[i] = ["Blade Flurry"]; i++;
nltalent[i] = ["Sword Specialization"]; i++;
nltalent[i] = ["Weapon Expertise"]; i++;
nltalent[i] = ["Blade Twisting"]; i++;
nltalent[i] = ["Vitality"]; i++;
nltalent[i] = ["Adrenaline Rush"]; i++;
nltalent[i] = ["Nerves of Steel"]; i++;
nltalent[i] = ["Throwing Specialization"]; i++;
nltalent[i] = ["Combat Potency"]; i++;
nltalent[i] = ["Unfair Advantage"]; i++;
nltalent[i] = ["Surprise Attacks"]; i++;
nltalent[i] = ["Savage Combat"]; i++;
nltalent[i] = ["Prey on the Weak"]; i++;
nltalent[i] = ["Killing Spree"]; i++;
treeStartStop[t] = i -1;
t++;

//subtlety talents
nltalent[i] = ["Relentless Strikes"]; i++;
nltalent[i] = ["Master of Deception"]; i++;
nltalent[i] = ["Opportunity"]; i++;
nltalent[i] = ["Sleight of Hand"]; i++;
nltalent[i] = ["Improved Sap"]; i++;
nltalent[i] = ["Camouflage"]; i++;
nltalent[i] = ["Elusiveness"]; i++;
nltalent[i] = ["Ghostly Strike"]; i++;
nltalent[i] = ["Serrated Blades"]; i++;
nltalent[i] = ["Setup"]; i++;
nltalent[i] = ["Initiative"]; i++;
nltalent[i] = ["Improved Ambush"]; i++;
nltalent[i] = ["Heightened Senses"]; i++;
nltalent[i] = ["Preparation"]; i++;
nltalent[i] = ["Dirty Deeds"]; i++;
nltalent[i] = ["Hemorrhage"]; i++;
nltalent[i] = ["Master of Subtlety"]; i++;
nltalent[i] = ["Deadliness"]; i++;
nltalent[i] = ["Enveloping Shadows"]; i++;
nltalent[i] = ["Premeditation"]; i++;
nltalent[i] = ["Cheat Death"]; i++;
nltalent[i] = ["Sinister Calling"]; i++;
nltalent[i] = ["Waylay"]; i++;
nltalent[i] = ["Honor Among Thieves"]; i++;
nltalent[i] = ["Shadowstep"]; i++;
nltalent[i] = ["Filthy Tricks"]; i++;
nltalent[i] = ["Slaughter from the Shadows"]; i++;
nltalent[i] = ["Shadow Dance"]; i++;
treeStartStop[t] = i -1;
t++;

//elemental talents
nltalent[i] = ["Convection"]; i++;
nltalent[i] = ["Concussion"]; i++;
nltalent[i] = ["Call of Flame"]; i++;
nltalent[i] = ["Elemental Warding"]; i++; 
nltalent[i] = ["Elemental Devastation"]; i++;
nltalent[i] = ["Reverberation"]; i++;
nltalent[i] = ["Elemental Focus"]; i++;
nltalent[i] = ["Elemental Fury"]; i++;
nltalent[i] = ["Improved Fire Nova Totem"]; i++;
nltalent[i] = ["Eye of the Storm"]; i++;
nltalent[i] = ["Elemental Reach"]; i++;
nltalent[i] = ["Call of Thunder"]; i++;
nltalent[i] = ["Unrelenting Storm"]; i++;
nltalent[i] = ["Elemental Precision"]; i++;
nltalent[i] = ["Lightning Mastery"]; i++;
nltalent[i] = ["Elemental Mastery"]; i++;
nltalent[i] = ["Storm, Earth and Fire"]; i++;
nltalent[i] = ["Booming Echos"]; i++;
nltalent[i] = ["Elemental Oath"]; i++;
nltalent[i] = ["Lightning Overload"]; i++;
nltalent[i] = ["Astral Shift"]; i++;
nltalent[i] = ["Totem of Wrath"]; i++;
nltalent[i] = ["Lava Flows"]; i++;
nltalent[i] = ["Shamanism"]; i++;
nltalent[i] = ["Thunderstorm"]; i++;

treeStartStop[t] = i -1;
t++;

//enhancement talents

nltalent[i] = ["Enhancing Totems"]; i++;
nltalent[i] = ["Earth's Grasp"]; i++;
nltalent[i] = ["Ancestral Knowledge"]; i++;
nltalent[i] = ["Guardian Totems"]; i++;
nltalent[i] = ["Thundering Strikes"]; i++;
nltalent[i] = ["Improved Ghost Wolf"]; i++;
nltalent[i] = ["Improved Shields"]; i++;
nltalent[i] = ["Elemental Weapons"]; i++;
nltalent[i] = ["Shamanistic Focus"]; i++;
nltalent[i] = ["Anticipation"]; i++;
nltalent[i] = ["Flurry"]; i++;
nltalent[i] = ["Toughness"]; i++;
nltalent[i] = ["Improved Windfury Totem"]; i++;
nltalent[i] = ["Spirit Weapons"]; i++;
nltalent[i] = ["Mental Dexterity"]; i++;
nltalent[i] = ["Unleashed Rage"]; i++;
nltalent[i] = ["Weapon Mastery"]; i++;
nltalent[i] = ["Dual Wield Specialization"]; i++;
nltalent[i] = ["Dual Wield"]; i++;
nltalent[i] = ["Stormstrike"]; i++;
nltalent[i] = ["Static Shock"]; i++;
nltalent[i] = ["Lava Lash"]; i++;
nltalent[i] = ["Improved Stormstrike"]; i++;
nltalent[i] = ["Mental Quickness"]; i++;
nltalent[i] = ["Shamanistic Rage"]; i++;
nltalent[i] = ["Earthen Power"]; i++;
nltalent[i] = ["Malestrom Weapon"]; i++;
nltalent[i] = ["Feral Spirit"]; i++;
treeStartStop[t] = i -1;
t++;

//restoration talents

nltalent[i] = ["Improved Healing Wave"]; i++;
nltalent[i] = ["Totemic Focus"]; i++
nltalent[i] = ["Improved Reincarnation"]; i++;
nltalent[i] = ["Healing Grace"]; i++;
nltalent[i] = ["Tidal Focus"]; i++;
nltalent[i] = ["Improved Water Shield"]; i++;
nltalent[i] = ["Healing Focus"]; i++;
nltalent[i] = ["Tidal Force"]; i++;
nltalent[i] = ["Ancestral Healing"]; i++;
nltalent[i] = ["Restorative Totems"]; i++;
nltalent[i] = ["Tidal Mastery"]; i++;
nltalent[i] = ["Healing Way"]; i++;
nltalent[i] = ["Nature's Swiftness"]; i++;
nltalent[i] = ["Focused Mind"]; i++;
nltalent[i] = ["Purification"]; i++;
nltalent[i] = ["Nature's Guardian"]; i++;
nltalent[i] = ["Mana Tide Totem"]; i++;
nltalent[i] = ["Cleanse Spirit"]; i++;
nltalent[i] = ["Blessing of the Eternals"]; i++;
nltalent[i] = ["Improved Chain Heal"]; i++;
nltalent[i] = ["Nature's Blessing"]; i++;
nltalent[i] = ["Ancestral Awakening"]; i++;
nltalent[i] = ["Earth Shield"]; i++;
nltalent[i] = ["Improved Earth Shield"]; i++;
nltalent[i] = ["Tidal Waves"]; i++;
nltalent[i] = ["Riptide"]; i++;
treeStartStop[t] = i -1;
t++;

//Affliction talents
nltalent[i] = ["Improved Curse of Agony"]; i++;
nltalent[i] = ["Suppression"]; i++;
nltalent[i] = ["Improved Corruption"]; i++;
nltalent[i] = ["Frailty"]; i++;
nltalent[i] = ["Improved Drain Soul"]; i++; 
nltalent[i] = ["Improved Life Tap"]; i++;
nltalent[i] = ["Soul Siphon"]; i++;
nltalent[i] = ["Improved Fear"]; i++;
nltalent[i] = ["Fel Concentration"]; i++;
nltalent[i] = ["Amplify Curse"]; i++;
nltalent[i] = ["Grim Reach"]; i++;
nltalent[i] = ["Nightfall"]; i++;
nltalent[i] = ["Empowered Corruption"]; i++;
nltalent[i] = ["Shadow Embrace"]; i++;
nltalent[i] = ["Siphon Life"]; i++;
nltalent[i] = ["Curse of Exhaustion"]; i++;
nltalent[i] = ["Improved Felhunter"]; i++;
nltalent[i] = ["Shadow Mastery"]; i++;
nltalent[i] = ["Eradication"]; i++;
nltalent[i] = ["Contagion"]; i++;
nltalent[i] = ["Dark Pact"]; i++;
nltalent[i] = ["Improved Howl of Terror"]; i++;
nltalent[i] = ["Malediction"]; i++;
nltalent[i] = ["Death's Embrace"]; i++;
nltalent[i] = ["Unstable Affliction"]; i++;
nltalent[i] = ["Pandemic"]; i++;
nltalent[i] = ["Everlasting Affliction"]; i++;
nltalent[i] = ["Haunt"]; i++;
treeStartStop[t] = i -1;
t++;

//demonology talents
nltalent[i] = ["Improved Healthstone"]; i++;
nltalent[i] = ["Improved Imp"]; i++;
nltalent[i] = ["Demonic Embrace"]; i++;
nltalent[i] = ["Fel Synergy"]; i++;
nltalent[i] = ["Improved Health Funnel"]; i++;
nltalent[i] = ["Demonic Brutality"]; i++;
nltalent[i] = ["Fel Vitality"]; i++;
nltalent[i] = ["Improved Succubus"]; i++;
nltalent[i] = ["Soul Link"]; i++;
nltalent[i] = ["Fel Domination"]; i++;
nltalent[i] = ["Demonic Aegis"]; i++;
nltalent[i] = ["Unholy Power"]; i++;
nltalent[i] = ["Master Summoner"]; i++;
nltalent[i] = ["Demonic Sacrifice"]; i++;
nltalent[i] = ["Master Conjuror"]; i++;
nltalent[i] = ["Mana Feed"]; i++;
nltalent[i] = ["Master Demonologist"]; i++;
nltalent[i] = ["Improved Enslave Demon"]; i++;
nltalent[i] = ["Demonic Resilience"]; i++;
nltalent[i] = ["Demonic Empowerment"]; i++;
nltalent[i] = ["Demonic Knowledge"]; i++;
nltalent[i] = ["Demonic Tactics"]; i++;
nltalent[i] = ["Improved Demonic Tactics"]; i++;
nltalent[i] = ["Summon Felguard"]; i++;
nltalent[i] = ["Demonic Empathy"]; i++;
nltalent[i] = ["Demonic Pact"]; i++;
nltalent[i] = ["Metamorphosis"]; i++;
treeStartStop[t] = i -1;
t++;

//destruction talents
nltalent[i] = ["Improved Shadow Bolt"]; i++;
nltalent[i] = ["Bane"]; i++;
nltalent[i] = ["Aftermath"]; i++;
nltalent[i] = ["Molten Core"]; i++;
nltalent[i] = ["Cataclysm"]; i++;
nltalent[i] = ["Demonic Power"]; i++;
nltalent[i] = ["Shadowburn"]; i++;
nltalent[i] = ["Ruin"]; i++;
nltalent[i] = ["Intensity"]; i++;
nltalent[i] = ["Destructive Reach"]; i++;
nltalent[i] = ["Improved Searing Pain"]; i++;
nltalent[i] = ["Pyroclasm"]; i++;
nltalent[i] = ["Improved Immolate"]; i++;
nltalent[i] = ["Devastation"]; i++;
nltalent[i] = ["Nether Protection"]; i++;
nltalent[i] = ["Emberstorm"]; i++;
nltalent[i] = ["Conflagrate"]; i++;
nltalent[i] = ["Soul Leech"]; i++;
nltalent[i] = ["Backlash"]; i++;
nltalent[i] = ["Shadow and Flame"]; i++;
nltalent[i] = ["Improved Soul Leech"]; i++;
nltalent[i] = ["Backdraft"]; i++;
nltalent[i] = ["Shadow Fury"]; i++;
nltalent[i] = ["Empowered Imp"]; i++;
nltalent[i] = ["Fire and Brimstone"]; i++;
nltalent[i] = ["Chaos Bolt"]; i++;
treeStartStop[t] = i -1;
t++;

//arms talents
nltalent[i] = ["Improved Heroic Strike"]; i++;
nltalent[i] = ["Deflection"]; i++;
nltalent[i] = ["Improved Rend"]; i++;
nltalent[i] = ["Improved Charge"]; i++; 
nltalent[i] = ["Iron Will"]; i++;
nltalent[i] = ["Tactical Mastery"]; i++;
nltalent[i] = ["Improved Overpower"]; i++;
nltalent[i] = ["Anger Management"]; i++;
nltalent[i] = ["Impale"]; i++;
nltalent[i] = ["Deep Wounds"]; i++;
nltalent[i] = ["Two-Handed Weapon Specialization"]; i++;
nltalent[i] = ["Taste for Blood"]; i++;
nltalent[i] = ["Poleaxe Specialization"]; i++;
nltalent[i] = ["Sweeping Strikes"]; i++;
nltalent[i] = ["Mace Specialization"]; i++;
nltalent[i] = ["Sword Specialization"]; i++;
nltalent[i] = ["Weapon Mastery"]; i++;
nltalent[i] = ["Improved Hamstring"]; i++;
nltalent[i] = ["Trauma"]; i++;
nltalent[i] = ["Second Wind"]; i++;
nltalent[i] = ["Mortal Strike"]; i++;
nltalent[i] = ["Strength of Arms"]; i++;
nltalent[i] = ["Improved Slam"]; i++;
nltalent[i] = ["Improved Mortal Strike"]; i++;
nltalent[i] = ["Juggernaut"]; i++;
nltalent[i] = ["Unrelenting Assault"]; i++;
nltalent[i] = ["Sudden Death"]; i++;
nltalent[i] = ["Endless Rage"]; i++;
nltalent[i] = ["Blood Frenzy"]; i++;
nltalent[i] = ["Wrecking Crew"]; i++;
nltalent[i] = ["Bladestorm"]; i++;
treeStartStop[t] = i -1;
t++;

//fury talents
nltalent[i] = ["Armored to the Teeth"]; i++;
nltalent[i] = ["Booming Voice"]; i++;
nltalent[i] = ["Cruelty"]; i++;
nltalent[i] = ["Improved Demoralizing Shout"]; i++;
nltalent[i] = ["Unbridled Wrath"]; i++;
nltalent[i] = ["Improved Cleave"]; i++;
nltalent[i] = ["Piercing Howl"]; i++;
nltalent[i] = ["Blood Craze"]; i++;
nltalent[i] = ["Commanding Presence"]; i++;
nltalent[i] = ["Dual Wield Specialization"]; i++;
nltalent[i] = ["Improved Execute"]; i++;
nltalent[i] = ["Enrage"]; i++;
nltalent[i] = ["Precision"]; i++;
nltalent[i] = ["Death Wish"]; i++;
nltalent[i] = ["Improved Intercept"]; i++;
nltalent[i] = ["Improved Berserker Rage"]; i++;
nltalent[i] = ["Shredding Blows"]; i++;
nltalent[i] = ["Intensify Rage"]; i++;
nltalent[i] = ["Bloodthirst"]; i++;
nltalent[i] = ["Improved Whirlwind"]; i++;
nltalent[i] = ["Furious Attacks"]; i++;
nltalent[i] = ["Improved Berserker Stance"]; i++;
nltalent[i] = ["Heroic Fury"]; i++;
nltalent[i] = ["Rampage"]; i++;
nltalent[i] = ["Bloodsurge"]; i++;
nltalent[i] = ["Unending Fury"]; i++;
nltalent[i] = ["Titan's Grip"]; i++;


treeStartStop[t] = i -1;
t++;

//protection talents
nltalent[i] = ["Improved Bloodrage"]; i++;
nltalent[i] = ["Shield Specialization"]; i++;
nltalent[i] = ["Improved Thunder Clap"]; i++;
nltalent[i] = ["Incite"]; i++;
nltalent[i] = ["Anticipation"]; i++;
nltalent[i] = ["Last Stand"]; i++;
nltalent[i] = ["Improved Revenge"]; i++;
nltalent[i] = ["Shield Mastery"]; i++;
nltalent[i] = ["Toughness"]; i++;
nltalent[i] = ["Improved Spell Reflection"]; i++;
nltalent[i] = ["Improved Disarm"]; i++;
nltalent[i] = ["Puncture"]; i++;
nltalent[i] = ["Improved Disciplines"]; i++;
nltalent[i] = ["Concussion Blow"]; i++;
nltalent[i] = ["Gag Order"]; i++;
nltalent[i] = ["One-Handed Weapon Specialization"]; i++;
nltalent[i] = ["Improved Defensive Stance"]; i++;
nltalent[i] = ["Vigilance"]; i++;
nltalent[i] = ["Focused Rage"]; i++;
nltalent[i] = ["Vitality"]; i++;
nltalent[i] = ["Safeguard"]; i++;
nltalent[i] = ["Warbringer"]; i++;
nltalent[i] = ["Devastate"]; i++;
nltalent[i] = ["Critical Block"]; i++;
nltalent[i] = ["Sword and Board"]; i++;
nltalent[i] = ["Damage Shield"]; i++;
nltalent[i] = ["Shockwave"]; i++;
treeStartStop[t] = i -1;
t++;

jsLoaded=true;//needed for ajax script loading
